# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1732178972a0f89bced162bbdc50bfeba3cbdfce8d17a28e8e12830d085ae2013a93bd8757c0a0cbd7752f6501533c9c0df94e739727414bb3fedb3f78602935

test:
  secret_key_base: 86fb7c55b1fff60cb0703c50c804036baff63f1e910ae1f80af9f4580e25b7981260e462210a31794f404e9e249c36bed8904ddfca3c7634077e41b9b9e9b6a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
